# Generated by Django 4.2.7 on 2023-12-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('recipe_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('food_id', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('amounts', models.TextField()),
                ('time', models.DecimalField(decimal_places=0, max_digits=10)),
                ('people', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
